core/urls.py
from django.urls import path
from .views import Core, CoreAjax

urlpatterns = [
    path('', Core.index, name='index'),
    path('get_edital_descricao_ajax', CoreAjax.get_edital_descricao, name='get_edital_descricao_ajax'),
    path('get_editais_filtros_ajax', CoreAjax.get_editais_filtros, name='get_editais_filtros_ajax'),
    path('validar_login_usuario', CoreAjax.validar_login_usuario, name='validar_login_usuario'),

    path('login', Core.login, name='login'),
    path('logout', Core.logout, name='logout'),
    path('usuario/novoUsuario', Core.novoUsuario, name='novoUsuario'),
    path('usuario/editarMeusDados', Core.editarMeusDados, name='editarMeusDados'),

    path('buscarEmailAjax', CoreAjax.buscarEmail, name='buscarEmailAjax'),
    path('buscarCpfAjax', CoreAjax.buscarCpf, name='buscarCpfAjax'),
    path('buscarCnpjAjax', CoreAjax.buscarCnpj, name='buscarCnpjAjax'),

    path('cancelarDocumentoRequisitoAjax', CoreAjax.cancelar_documento_requisito, name='cancelarDocumentoRequisitoAjax'),
    path('cancelarDocumentoUsuarioAjax', CoreAjax.cancelar_documento_usuario, name='cancelarDocumentoUsuarioAjax'),

    path('getBlocosCamposArquivosServicosAjax', CoreAjax.get_blocos_campos_arquivos_servicos, name='getBlocosCamposArquivosServicosAjax'),


]

credenciamento/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

import private_storage.urls


admin.site.site_header = 'Federação das Indústrias do Estado do Piauí'
admin.site.index_title = 'Credenciamento'
admin.site.site_title = 'Administrador'

urlpatterns = [
    path('admin/', admin.site.urls),
    path('documento_privado/', include('private_storage.urls')),
    path('', include('core.urls')),
    path('edital/', include('edital.urls')),
    path('usuario/', include('usuario.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

usuario/urls.py
from . import util
from django.urls import path
from django.contrib.auth import views as auth_views


urlpatterns = [

    path('senha/resgatar/',
         auth_views.PasswordResetView.as_view(template_name='usuario/email/password_reset.html'),
         name='password_reset'),

    path('senha/envio/',
         auth_views.PasswordResetDoneView.as_view(template_name='usuario/email/password_reset_done.html'),
         name='password_reset_done'),

    path('senha/resgatar/novaSenha/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='usuario/email/password_reset_confirm.html'), name='password_reset_confirm'),

    path('senha/resgatar/confirmacao/',
         auth_views.PasswordResetView.as_view(template_name='usuario/email/password_reset_complete.html'),
         name='password_reset_complete'),

    path('ativarAcesso/<uidb64>/<token>/', util.ativarAcesso, name='ativarAcesso')

]

edital/models.py
from django.db import models
from core.ferramentas.enumerate import STATUS_EDITAL, CATEGORIA_EDITAL, STATUS_INSCRICAO, STATUS_DOCUMENTO_REQUISITO_INSCRICAO
from private_storage.fields import PrivateFileField

def get_path_private(instance):
    return "/{}".format(instance.inscricao.usuario.id)


class Edital(models.Model):
    """
        *   Classe Edital
        *   Classe que destinado aos editais publicados
    """

    status = models.CharField(max_length=30, choices=STATUS_EDITAL, default='0')
    titulo = models.CharField(max_length=250, verbose_name='Título', null=True)
    codigo = models.CharField(max_length=250, verbose_name='Código', null=True)
    categoria = models.CharField(max_length=60, choices=CATEGORIA_EDITAL, verbose_name='Categoria')
    descricao = models.TextField(verbose_name="Descrição", null=True)
    contratante = models.ManyToManyField('core.contratante', related_query_name='+')
    servicos = models.ManyToManyField('core.servico', blank=True, related_query_name='+')
    documentos_usuario = models.ManyToManyField('core.DocumentoUsuario', blank=False, related_query_name='+')
    data_publicacao = models.DateTimeField(verbose_name='Data de Publicação')
    ano_publicacao = models.CharField(max_length=5, verbose_name='Ano de Publicação', blank=True, null=True, editable=False)
    inicio_inscricao = models.DateTimeField(verbose_name='Inicio das Inscrições')
    fim_inscricao = models.DateTimeField(verbose_name='Fim das Inscrições')
    created_at = models.DateTimeField('Criado em', auto_now_add=True, null=True)
    update_at = models.DateTimeField('Atualizado em', auto_now=True, null=True)

    class Meta:
        # ordering = ['-id']
        verbose_name = 'Edital'
        verbose_name_plural = 'Editais'

    def save(self, *args, **kwargs):
        self.ano_publicacao = self.data_publicacao.strftime("%Y")
        super(Edital, self).save(*args, **kwargs)

    def __str__(self):
        return self.titulo

    def get_categoria(self):
        return CATEGORIA_EDITAL[int(self.categoria)][1]

    def get_status(self):
        return STATUS_EDITAL[int(self.status)][1]


class Inscricao(models.Model):

    usuario = models.ForeignKey('usuario.Usuario', on_delete=models.CASCADE)
    edital = models.ForeignKey(Edital, on_delete=models.CASCADE)
    status = models.CharField(max_length=100, choices=STATUS_INSCRICAO, default='0', verbose_name='Status geral')
    servicos = models.ManyToManyField('core.Servico', blank=False)
    created_at = models.DateTimeField('Criado em', auto_now_add=True, null=True)
    update_at = models.DateTimeField('Atualizado em', auto_now=True, null=True)

    class Meta:
        verbose_name = 'Inscrição'
        verbose_name_plural = 'Inscrições'

    def __str__(self):
        return self.usuario.email


class DocumentoUsuarioInscricao(models.Model):
    status = models.CharField(max_length=100, choices=STATUS_DOCUMENTO_REQUISITO_INSCRICAO, default='0', verbose_name='Status do Documento')
    observacao = models.TextField(verbose_name='Observações', blank=True)
    documento = PrivateFileField(verbose_name="Documento", upload_subfolder=get_path_private, blank=True, null=True)
    inscricao = models.ForeignKey(Inscricao, on_delete=models.CASCADE, null=True, blank=False)
    documento_usuario = models.ForeignKey('core.DocumentoUsuario', on_delete=models.CASCADE, null=True, blank=False, editable=False)
    created_at = models.DateTimeField('Criado em', auto_now_add=True, null=True)
    update_at = models.DateTimeField('Atualizado em', auto_now=True, null=True)

    class Meta:
        verbose_name = 'Documento Pessoal do Usuário'
        verbose_name_plural = 'Documentos Pessoais dos Usuários'

    def __str__(self):
        return  '{}'.format(self.documento_usuario.titulo)

    def get_nome_documento(self):
        return self.documento.name.split('/')[1]

    def get_status(self):
        return STATUS_DOCUMENTO_REQUISITO_INSCRICAO[int(self.status)][1]


class DocumentoRequisitoInscricao(models.Model):
    servico = models.ForeignKey('core.Servico', on_delete=models.CASCADE, null=True)
    status = models.CharField(max_length=100, choices=STATUS_DOCUMENTO_REQUISITO_INSCRICAO, default='0', verbose_name='Status do Documento')
    observacao = models.TextField(verbose_name='Observações', blank=True)
    inscricao = models.ForeignKey(Inscricao, on_delete=models.CASCADE, null=True, blank=False)
    requisito = models.ForeignKey('core.Requisito', on_delete=models.CASCADE, null=True, blank=False, editable=False)
    documento = PrivateFileField(verbose_name="Documento", upload_subfolder=get_path_private, blank=True, null=True)
    created_at = models.DateTimeField('Criado em', auto_now_add=True, null=True)
    update_at = models.DateTimeField('Atualizado em', auto_now=True, null=True)

    class Meta:
        verbose_name = 'Documento Requisitado'
        verbose_name_plural = 'Documentos Requisitados'

    def __str__(self):
        return  '{} / {}'.format(self.requisito.titulo, self.servico)


    def delete(self):
        # Remova o serviço caso não tenha mais nenhum documento do mesmo na inscricção
        len_documentos = len(DocumentoRequisitoInscricao.objects.filter(inscricao=self.inscricao, servico=self.servico))
        print(len_documentos)
        if len_documentos == 1:
            self.inscricao.servicos.remove(self.servico)

        super(DocumentoRequisitoInscricao, self).delete()

    def get_nome_documento(self):
        return self.documento.name.split('/')[1]


    def get_status(self):
        return STATUS_DOCUMENTO_REQUISITO_INSCRICAO[int(self.status)][1]

usuario/models.py
from django.db import models
from core.ferramentas.enumerate import ESTADOS, SEXO, CATEGORIA_PESSOA
from django.contrib.auth.models import User

class Usuario(models.Model):
    """
        *   Classe Usuario
        *   Classe que extende a classe padrão `user` com objetivo de acrescentar mais atributos
    """
    categoria_pessoa = models.CharField(max_length=1, choices=CATEGORIA_PESSOA, blank=False, null=True)
    ativo = models.BooleanField(verbose_name='Ativar essa Conta ?', default=False)
    user = models.OneToOneField(User, verbose_name='Usuário de acesso', on_delete=models.SET_NULL, null=True)
    nome = models.CharField(max_length=150, verbose_name='Nome', null=True, blank=True)
    email = models.CharField(max_length=150, verbose_name='* E-mail', null=True)
    cpf = models.CharField(max_length=50, verbose_name='CPF', blank=True, null=True)
    razao_social = models.CharField(max_length=150, verbose_name='Razão Social', blank=True, null=True)
    nome_fantasia = models.CharField(max_length=150, verbose_name='Nome Fantasia', blank=True, null=True)
    cnpj = models.CharField(max_length=50, verbose_name='CNPJ', blank=True, null=True)
    cnpj_cpf = models.CharField(max_length=50, verbose_name='Cpf do Responsável', null=True, blank=True)
    cnpj_nome = models.CharField(max_length=150, verbose_name='Nome do Responsável', null=True, blank=True)
    sexo = models.CharField(max_length=1, choices=SEXO, default='0', blank=True, null=True)
    telefone = models.CharField(max_length=20, verbose_name='Telefone', null=True, blank=True, default='')
    endereco = models.CharField(max_length=100, verbose_name='Endereço', null=True, blank=True, default='')
    numero = models.CharField(max_length=10, verbose_name='Número', default="S/N", null=True, blank=True)
    complemento = models.CharField(max_length=50, null=True, blank=True, default='')
    bairro = models.CharField(max_length=50, verbose_name='Bairro', null=True, blank=True, default='')
    cidade = models.CharField(max_length=50, verbose_name='Cidade', null=True, blank=True, default='')
    cep = models.CharField(max_length=20, verbose_name="Cep", null=True, blank=True, default='')
    estado = models.CharField(max_length=2, choices=ESTADOS, verbose_name='Estado', null=True, blank=True, default='PI')

    class Meta:
        verbose_name = 'Usuário'
        verbose_name_plural = 'Usuários'

    def __str__(self):
        return self.email

    def get_categoria_pessoa(self):
        return list(filter(lambda c: c[0] == self.categoria_pessoa, CATEGORIA_PESSOA))[0][1]

usuario/templates/usuario/elementos/modalLogin.html
<div class="modal fade" id="login_modal" aria-hidden="true">
    <div class="modal-dialog ">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">LOGIN</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="id_modal_body_edital_descricao">
                <div class="card">
                    <div class="card-body" style="padding: 40px;">
                        <form id="login" class="nobottommargin" method="POST">
                            {% csrf_token %}
                            <input id="comando" name="comando" value="#login#" hidden>
                            <input id="id_inscricao" hidden>
                            <div class="col_full">
                                <label for="email_login">Email:</label>
                                <input type="email" id="email_login" name="email" value=""
                                       class="form-control not-dark" required/>
                            </div>
                            <div class="col_full">
                                <label for="senha_login">Senha:</label>
                                <input type="password" id="senha_login" name="senha" value=""
                                       class="form-control not-dark" required/>
                            </div>
                            <div class="col_full nobottommargin">
                                <button id="button_entrar" class="button button-border button-rounded button-fill fill-from-right button-blue">
                                    <span>Entrar</span>
                                </button>
                            </div>
                            <div class="row mt-4" style="font-size: 15px;">
                                <div class="col-sm-12 md-12" style="text-align: end;">
                                    <a href="{% url 'password_reset' %}">RESGATAR ACESSO</a>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

usuario/templates/usuario/elementos/modalMeusDadosPessoaFisica.html
<div class="modal fade" id="modal_meus_dados" aria-hidden="true">
    <div class="modal-dialog modal-xl">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Meus Dados</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <div class="card">
                    <div class="card-body">
                        <form id="id_form_meus_dados_pessoa_fisica" method="POST">
                            {% csrf_token %}
                            <input id="comando" name="comando" value="#editar#" hidden>
                            <input name="categoria_pessoa" value="0" hidden>
                            <div class="form-row">
                                <div class="form-group col-md-8">
                                    <label for="nome">Nome Completo</label>
                                    <input type="text" class="form-control" id="nome"
                                           name="nome" value="{{usuario.nome}}">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="email">Email</label>
                                    <input type="text" class="form-control" value="{{usuario.email}}" disabled>
                                </div>
                            </div>

<!--                            <div class="form-row">-->
<!--                                <div class="form-group col-md-6">-->
<!--                                    <label for="senha">Senha</label>-->
<!--                                    <input type="password" class="form-control" id="senha" name="senha" required>-->
<!--                                </div>-->
<!--                                <div class="form-group col-md-6">-->
<!--                                    <label for="csenha">Confirmar Senha</label>-->
<!--                                    <input type="password" class="form-control" id="csenha" name="csenha" required>-->
<!--                                </div>-->
<!--                            </div>-->

                            <div class="form-row">
                                <div class="form-group col-md-3">
                                    <label for="cpf">CPF</label>
                                    <input type="text" class="form-control" data-mask="999.999.999-99"
                                           data-mask-selectonfocus="true" value="{{usuario.cpf}}" disabled>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="sexo">Sexo</label>
                                    <input type="text" id="sexo" name="sexo" hidden>
                                    <select id="select_sexo" class="form-control"
                                            onchange=" $('#sexo').val($(this).val())">
                                        <option value="0">Masculino</option>
                                        <option value="1">Faminino</option>
                                    </select>
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="telefone">Telefone</label>
                                    <input type="text" class="form-control" data-mask="(99) 99999-9999"
                                           data-mask-selectonfocus="true" id="telefone" name="telefone" value="{{usuario.telefone}}"
                                    >
                                </div>
                                <div class="form-group col-md-3">
                                    <label for="estado">Estado</label>
                                    <input type="text" id="estado" name="estado" hidden>
                                    <select id="select_estado" class="form-control"
                                            onchange=" $('#estado').val($(this).val())">
                                        <option value="">Selecione</option>
                                        <option value="AC">Acre</option>
                                        <option value="AL">Alagoas</option>
                                        <option value="AP">Amapá</option>
                                        <option value="AM">Amazonas</option>
                                        <option value="BA">Bahia</option>
                                        <option value="CE">Ceará</option>
                                        <option value="DF">Distrito Federal</option>
                                        <option value="ES">Espirito Santo</option>
                                        <option value="GO">Goiás</option>
                                        <option value="MA">Maranhão</option>
                                        <option value="MS">Mato Grosso do Sul</option>
                                        <option value="MT">Mato Grosso</option>
                                        <option value="MG">Minas Gerais</option>
                                        <option value="PA">Pará</option>
                                        <option value="PB">Paraíba</option>
                                        <option value="PR">Paraná</option>
                                        <option value="PE">Pernambuco</option>
                                        <option value="PI">Piauí</option>
                                        <option value="RJ">Rio de Janeiro</option>
                                        <option value="RN">Rio Grande do Norte</option>
                                        <option value="RS">Rio Grande do Sul</option>
                                        <option value="RO">Rondônia</option>
                                        <option value="RR">Roraima</option>
                                        <option value="SC">Santa Catarina</option>
                                        <option value="SP">São Paulo</option>
                                        <option value="SE">Sergipe</option>
                                        <option value="TO">Tocantins</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-2">
                                    <label for="cidade">Cidade</label>
                                    <input type="text" class="form-control" id="cidade" name="cidade" value="{{usuario.cidade}}">
                                </div>
                                <div class="form-group col-md-10">
                                    <label for="endereco">Endereço</label>
                                    <input type="text" class="form-control" id="endereco" name="endereco" value="{{usuario.endereco}}">
                                </div>
                            </div>

                            <div class="form-row">
                                <div class="form-group col-md-4">
                                    <label for="numero">Número</label>
                                    <input type="text" class="form-control" id="numero" name="numero" value="{{usuario.numero}}">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="bairro">Bairro</label>
                                    <input type="text" class="form-control" id="bairro" name="bairro" value="{{usuario.bairro}}">
                                </div>
                                <div class="form-group col-md-4">
                                    <label for="CEP">CEP</label>
                                    <input type="text" class="form-control" id="CEP" name="cep" value="{{usuario.cep}}">
                                </div>
                            </div>

                            <div class="row">
                                <div class="col-md-12" style="text-align: end;">
                                    <button type="submit" id="button_enviar"
                                            class="button button-rounded button-reveal button-blue"><i
                                            class="icon-send"></i> <span
                                            style="color: #fff;">Salvar Meus Dados</span>
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $("#select_sexo").val('{{usuario.sexo}}').change();
    $("#select_estado").val('{{usuario.estado}}').change();
</script>